language: node_js
node_js:
  - "10"
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
before_script:
  - pip install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
script:
  - yarn build
after_success:
  # Delete bucket content
  - aws_access_key_id=${AWS_ACCESS_KEY_ID} aws_secret_access_key=${AWS_SECRET_ACCESS_KEY} aws s3 rm s3://sh.diogocardoso.me --recursive --region eu-west-2
deploy:
  provider: s3
  access_key_id:
    secure: "Xb82RW/u7UyJf2Mv4xB9kVz1s50AaPE6BgC/lsBkfe5qetoNhW4+SYyYDdx7g1pCBEXM7GBYMcOCd/GKzzpDGLTNXBDABiLOB0H8BCgZaKOT6o8NTWtAsBEeZekVB28lWhPqz4cq5Km6qW1JsZ5RsT+uLKpJAjIuo49Knl6s/SuMY+LjxKnn0jYva8ymXCsmAKju5nQgHGBadMalHiV8YefdNmCNrFZsak+nNeCUH5oI2DKEU72bBIlpTQu5DYlsItHYsFXD/NMYvZS6CFv2JJhbzpLrOK7WEi2wQu+stHtIMnAQMcQpSDGMaLWFOSdcejFBIaWVrJUbxa060S6xZELFcAy8j3uNityst81fkYu1kNiBsTkwnokx0qQnJ8V4uBxrwqnHpaO4UBAs2pTKx5jgu3XO8In8nABogpyyKdDso4r6YQHJPqQ+MHy4VsYkPkOSp6uHEjLyViW+x6e3X+OwYo4R8J57lUCNkSrJJZT0qC95ATRnbZe9PXG3bGZJYAEgH0t7QsoFd128Y9ovTutYvfCSI0cKaBs5J2ZXrq1Q5sZnII+12Ab7GruuYB9scDnHMVbT/EbhRwuqCq7HJqnh4gJhlOL4ImT23j/c4Xiqax0r7XGa+zhrf6DW5TG8bhDGyD60YTXmwNPAfbKvaGOW+zkr9vvWGCZnRo/DD9o="
  secret_access_key:
    secure: "Jqqrfumb8WkzYlv01OTjB4JAY/3jeAcqHhh8IbWBOX6lrDfiMzQEQSabZKk8vo71IVUXPFWGHLwnMrPj1Lpc6cN21FySyrDjomwXs2Qjfp4F4wVjedHJfgmXRM3c2jQLBJeVazkHuCVFZKq6lfvq6zCt9w+amuXeui4aPBMQK3rwcLuiTIq8+NgUINPxy/yNCneDdgg8T8c2ahtYlTt7R5AhQ+2+q4CTT8prziHOdW2XCz1ovcOTejqZMolAP2HLebA/vrASvlY44Y1uHxeHA+c+tFvYHSfDX2ka12QNOMTJ5SzqpxuIW1OJBMkCAPR06Ple4UNc8rV9jEpbKsYsz9lHwDY0Gat1iRfn9uqZpmed+cIJ3xLzu7JF3toO44SCoqJlCYpVzZeT/i6XpzzjA1dccmvgxNzHA+ynllUjWljniod9pMC7LoEjloJF2HM4OajFN2LjadwP2CG2n7baKdFI6nvedhfdse7ayKv4CgoudZEFNjk5X0N6qMdUc6cSEcIFRF6kMDrvf0QDFH+7hfGkE8TZN+B84fZb7z53YJcXdAlnuXyhV6+d6vV0DaJJBKMFPKoNyJO2s+m5laZtvpJYosp00ZLaBKGjX1SQJZe8Hd58CMe4s31LLNyL5fDnhTg3mqTSRXG4V/ULP0WGq756ppHT8XGHm5WZ8Ya5t0Y="
  bucket: psd.diogocardoso.me
  # Prevent Travis from deleting the build artifacts
  skip_cleanup: true
  region: eu-west-2
  # Deploy a single folder and not the entire project
  local_dir: dist
after_deploy:
  - aws_access_key_id=${AWS_ACCESS_KEY_ID} aws_secret_access_key=${AWS_SECRET_ACCESS_KEY} aws cloudfront create-invalidation --distribution-id ${CF_DISTRIBUTION_ID} --paths "/*"
notifications:
  email: false
env:
  global:
    # CF_DISTRIBUTION_ID - Cloudfront Distribution ID
    - secure: "BcLNP8P+iRpeUNL4t55g/uh5PJeIkJkGyE5h0jRoYlAPTeQuSxBsM4tv6mb4Y+p3HwOY38wh1TWsubdo16JQahyp/We1Y0s6pbmvlA0K8MhnujlyPvqgnjZOjPtulxtwA99m/czZQSAhp/hIZ7QxSOLxeFJDxltPAGD/AwMcRvCkfKFjHi5ifH1EZGLe8c8CpTICTWmp6wQCvTEoqtKArN9+XK7KbI1ehFQy/3TgR8S6AOwxEfyU4s7E4pqsq8mL4t0XgeWGTi2Usb7XCapWvVRJbwayG9ilnqnsf70FfyFE9WCrheNtvO4tFlS+eeuJ0mtt+usYZnyrhrX9NlPP+3jRvZE4PhC+X1KNd9LPsOKKsoevO7sRSB9mIyYh44R+8QTZrThRJ8IdpRNtj/mrmPtBH8fEiaUIoSkfDMWg5BqEfcrhHkhoDIuPMna9La6Ei6dOin4S4FDy/SyHApPVRzqQeqxRqZU/MtU7UNiPM09Ec6NBvm9K3m4yIyNk428Gn4i+8c98rBdR/0AJXd85GNu0Fjp4J3Uo2VChYv40mtHPwtiXA1Xv5fXZStzbs31bdh8z/tx1F7K3EwWnd3JrDUTvYmfJ2C5RQr5NJNqIr/S0bp+GL48xi1b2Kjh8o3i8Sx7SisTd2VIlxjpJC6k6qgFCEM9DA5EPPGY2+A4NiBw="
    # AWS_ACCESS_KEY_ID - AWS Access Key ID
    - secure: "HCQmgNraj9vmMVT0P5svRAFir5d9btZ+Y+Ctnyn7ORehbn/N9lqq61ULcrSsyTVzwKaGbx5sa1wTfoNtIr6NpqKphj9RS4NINTNeyjYDK/ujnoxbGMcJ00SJAQcWn1GPU83iq6zjWX2YDC9JvCm2m6VTjNRs+2TWB5Ym2OMuCk0jLgyNPK4Cb2CPL9/JCNY6dpB5N4RAI/avodefmA2+MtZXQ6aXEe+KCrn+ZD7bkA0fLP9Syr31T1NXHBbZ7sDr0TonLAfxkp0QnXBvDeUKiZ1X6QQAHYDYT89iNIJjpW68cMLkTKlq4A2ZhF4pbM8LCKZxVHPNRVjz6P94I8HTAHl6x8yVu8Lt4WbdOMs2MS5rkBRo7nu6pTVzRa25Gjkr/wFD+uWIo1ZpMTXBJZK51ei50z8yHVn/1EIh+ViXUuyAeNbUThfZ27+O9BG2ELmzbaWJDnGpk6w4L69nvq28OiAm5/3e7nPtjXY3q8M+3IUW63SmRzFi3y/IZGODEQ7aGCm5d5EcKo5AZ9J3J1F8VgFmvIhxNr09mbT1sxX/yznrgWAeyEmhUVIkGjEcKy9KCmM9/WS5nTVhSZw3ocGSXls0AoTYX7Npbt02/wYGN64qFI22fCLzwctdO3C3XPa1ci/JWcqWwptW+CGGpt8ZfLVrlqtPrdav7JTZESEFARI="
    # AWS_SECRET_ACCESS_KEY - AWS Secret Access Key
    - secure: "aGIZ5p6erEfGv33av8shKJ1b4JNn6BmqQJ+pv/E6JFWAuqv5jgk3KValDlUXewoEREhRiHTEAKtZ0ddihtOsuTUTxRwbyndwhSW+UNkVvmbc4yCafKNe8QVQ9eSxQ7D0xQpIlGw18+oRyo8BR0QlrZfkQd3Ow3nbr4T3hWdbN9LkhMQTQav5HvqCSuNFrK6hWZkNYmKbvScmxfrSgyBlRBD8VPj9Gn5J4injmLBgR0Ya2RmP5UegBVgRUjm6RkBT8HY41CqkBZsdO9fY9SmqgoReOJ4KoZOu6SREaf+mpBmr8Oj6t3sDUy8OfsdRaLQOSwXjf1DK3ZRkrzIvrCXTW5ZJNKnANWGf+A+mPiuEZ70f8vBQ1aq7KA0VNYrqpyDoYhaI/3zPcjdqR1tjnghDuoZiX6qj27iXTQ3NmmN4uHndYtWR7AM3CZ0MQ20fmMFAigkBjPoEOTyLYfNPraHSgY2ItUMD6XjQC7dOmD3oP4Me73t/Zc06MYqI12mfRiw9mUMmS+UjcYMQTVp/6VMTx4Qpm2jZJ+lT4mkKk2ZMY9AZeq1Y81qKcuXZBch0rAK61pu2+PXernA93PKmC9wxjKPm5AswhVI5lQwo+rxvRvUwpu9pDpRG5ppIKNyUgSXYq4zQa7/DibwrzqiUtK31fGbFv6cu/T+CtxfsnbJXSyk="
