language: node_js
node_js:
  - "10"
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
before_script:
  - pip install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
script:
  - yarn build
after_success:
  # Delete bucket content
  - aws_access_key_id=${AWS_ACCESS_KEY_ID} aws_secret_access_key=${AWS_SECRET_ACCESS_KEY} aws s3 rm s3://sh.diogocardoso.me --recursive --region eu-west-2
deploy:
  provider: s3
  access_key_id:
    secure: "FYvMw9pyS6bGGZpGI6ahwVq7lsigujVHJPvUfOUQcpP7pJcXnM40lkj7FRQOEKeOzA6Ovozb2B9T81NTdTtT11xOImZLwgyrmSseXsT72BZ70B8XyCbc7w+0qazJZ6VjlpceRtwqzhDmYUhvz4XcyD6STiS1rBLdV/JpParFKjek5+6CfB8BfUP5XoICWiVTfnNUe+Y8wuY5dWxa4Qre2gxhh+AaZM01RLtHdEgUeoBrzNbQNkv4KjprG4GyMeoNcxoEhh+TlxMjClhKndpcngP/13p5bdWwYQfztnRMD/ybaD61bqpLL9uAGVxqowu2sDVCLnCDfgehTYpZtmTfi+6C2XAS0cwNlWwP/8gFxL8YNaxmuSSsvD1a1/9Yp8iqsg5gQd8Z4q3OzEUpQSt2RMSAnaLFvu7+dSfHM9uoxwFccv0dGBJF+ZQNS06p5QqYcMIHffQcY50/aOUJPHO/dJXg270hbhNEsdkr5N0ipGtJNPnmxXczEARU2kRucflseM6Jimy/CmFV8By27IZuk1wOK05etkcseUD7+qnKKRMgOeuoXWPDAlMwzODzzLy7r9GAqzk86ZD/xii7VvbTSYgbhoP3yoCJVjeX19xu9IJpyY+Ec6NIxgH667cURr/RGsonfGNYDBqKkUHr5TYXsekEacgvbDHXUyornHhVdig="
  secret_access_key:
    secure: "AlSo4gYzRAAgAjltPT3uLDuNbxFxGysoAjfJHKnrFHJBQZSXOycZYL4Io3IwlbOHcKeNsJ/H+d4TZlAC/MFxT5KEpuCd0RPEyMGParNGHLTP6gYuQzvp6xLxq8SOyXosXwhxuvmILv+GVx9J8WKBvvLQb7FzSBK0p++0v+SVfkdrq9fJTvRJ/h4OJ0HkGW5ZUc5ZYvwxDsdWNjF/XEbwZRRdhor3ZprnZSQgfPsMiu2pLKS6yMh0BM057ZGvs7jZM1InSu5zYCC7YuTjvGNpLP7hbSCg44cw8ZZMr5IKlyaZhDz75wHgMyXyQPr7+VOfU4bl0N2lej6gc26moZrq0w+AqZGRE0QJPW/gxseqX4yH4jUa2BeeHXa2b5jV5qBxIYR7gS2Jmlpo4Kg7h9w781x9FEIRsXeiE64AgtbUQfPNIGIsYWqlPqzSLwmgFqfoyfc0J2E/qDqA6w1kjiZg0RC+FKvkP8uUbI/o6TgZTQa1q8lXrzBNVGlpjSfRaBuJ1kOokbByxCu7Cezt+E9ammdOswHUK1gVyQzaI+gRFVuGtd/kCeVVvRzqIHDerxGdffEwEAlaIEY1ZucnDxWzYSVo/0ffXV6SjrGCRyAHKP4BTcPx94aeTFqNAJK8JygiPwqIS1qqFZQYbvDtCvdMpzFqwAAaxuobL3Imdjb41xw="
  bucket: psd.diogocardoso.me
  # Prevent Travis from deleting the build artifacts
  skip_cleanup: true
  region: eu-west-2
  # Deploy a single folder and not the entire project
  local_dir: build
after_deploy:
  - aws_access_key_id=${AWS_ACCESS_KEY_ID} aws_secret_access_key=${AWS_SECRET_ACCESS_KEY} aws cloudfront create-invalidation --distribution-id ${CF_DISTRIBUTION_ID} --paths "/*"
notifications:
  email: false
env:
  global:
    # CF_DISTRIBUTION_ID - Cloudfront Distribution ID
    - secure: "vXoGaAgKpoLUDODCTqpiR08AO6KX+Xw0B785cSHdRqIf+J9nc/K456XO8B3zAS/oCD3IWksj3mlug1cTAf190pK+GGpUGxw70bnP3uaBcAdnhCsaufRz2xHANIYXMACAGubFZ5wJakTXSzV7L0MHj+9pJ319bijuHxoSNwnhmAonhr1I/KZPrmf4s4t69X0VzbEJbSVdPl9+Fq0rnXgVi2wzydRP4+Il4lYYXdTL06zZzyXhIT9C5tHbB/MvsFADXgr9g3hIJHkZeozMhJW2Jwsqpal6yoFFtb7o7i/VXedG3dt9g9FwaJhLm5EhUB0JpbIDemMLtQune70/AQtU1PZlMZ/FgEY4juS7M3rd1zlhaqmXGMg0y50LkiqOCn21Od3qXvfIU+Tde0KPyBpEitvsKpRkjdwjpUTDFUGXQyl5vPYuIFoihXJuFpbZAHICg2EOaiPvEUpBZv5cKcoe+oZSglUUegV/aUsrlgjDLaAzzp0Wi16eHWC4oQ0D+GrU6Q4sXKUsV8Fhm1hFUMeztBBJHD7Ku51z/Bo5kDrvxEilf2gElu4Jk79EKdvx5Ngmlaf4V3QCqko0r2Ea6jLvOkdAYpQIvkc5Z5ZikKprvwbkp8EM4RZ2wM0s68lYDH7RLDuMFiRhp0ehBgaB0B0/OGNhmgf0qerpbZkWpKtgMaU="
    # AWS_ACCESS_KEY_ID - AWS Access Key ID
    - secure: "pZhkaYTGrweOe2rmrsGhWX7DH6tdF56UN3stOPWIEn9BGqIQjxAXNXOCUv25wSwzuoA21NcCqhTU8zVkIGacdKRy9BqJydbsqe0v+IJtGi4mc0X3YahmoRm2/eaywN1HtXxOzQyiSAOaOqDL3dWVeGfNY4rr2u/tcVa/uUjg+9ddm0wf9U0xCZ6gEIgEjcTl88rzFMPkBbFqx1LEuLDpGJ4DBdhqt7uQpb81WAzWA54c1+nHXa+cvcgY/tsf5jtPgjOyMOGnRa6ePyVkade3yw405uZI5XSbhuPrlDAfAwBj4EJSLtiCCsOc6n1e3ITsiF7HVmQOeG2V+ptPge34HCxyyMtyDOzzy/WNoMq6AWv9DEL3PsdOgZYyZVdflIuOP7vWuCWUCOIeTp9tvj5IiEJfep1Zwo1EXsVCnckCwqVGY0jYCj+esrPAbLAwJIWhBLfHXb9RgPTrhXuDdRFHMGhfhYSJVXv561yZDGDlFgLAF+0E/1KAXqHrW0f6Zq1EBIlFmCtGrXOJeLOpzFjgSwcWR7Gy4PGLh3ZyfmLO23lhPtGTl9DogB1jhgIZ6NLYMg14XqiHFwP0BAhLzuOneWkT92xw+mdgIIiLPs16mm+jjjxRo8x4n3ABV/ElNevX0D4F7tzkccpoyOaJjGXW1H6mBSZTvoo5F0Xu2vxGCtU="
    # AWS_SECRET_ACCESS_KEY - AWS Secret Access Key
    - secure: "RdvLyWz3+xbs+qd7qfJMVFrtRwa3Njv4t3ZNYI5m+iNJ7jZbbn4XCSsq31m2uscavkmkj2o+LqN7Ksj7xnpTuRCUK6Rznx5A5WuQcYQjx8k/jUUPsnq5IO61AZHBXDAa0gKXavrJqaBQ0eWUID36gDVyZ76DiyYxzA8LjRkS1glU8K61WHtc3u8yKHjaQ/qJ9p1s+Pzu5DU15+Ja5Hf8MjoYJ3HDiyIcXuB48R8VJUYJpllxJjCyC7rC7KNVs6FS3H/t1M1qpanSTImBh7soL6KODXzmjTfx+yaZvtnBjgxlDFfIpfEVe0+LNzZUj+ayYUNPWKRO7iF4RdRSzXPFHkzREpmGoIkCJ+zO5f1MH9ZPLd4vDxvoKbBRNPqr5GF1y5uukhdq2z+Ek0zbkd3y4xrKNXVMBWVbHd+F6ET5PJGKkYVH94JcLYqHJ/0S4dfjCo4IxbV5068SOoMO2aYwouNd/zifh45kuSLQQzj3a33Pw+1eDeP7CGnkmRJkMiA1ZQMmJmD6XgW9IQZH12gcpCbgYMvCF9ECRfC2ltqTCMACO4bC8rd31veURnlOfU5fiW/22vfM5y8R+keqrQh++1DI189ZsLd2/dpLxA6sE1jI+/qAFOOPam12lEQGo3zOY6sMe++E5k7+3CeR8vhdFFa5Ea11pym9hVSmwzNxVT8="
